// Generated by gencpp from file app2_package/AddTwoInts.msg
// DO NOT EDIT!


#ifndef APP2_PACKAGE_MESSAGE_ADDTWOINTS_H
#define APP2_PACKAGE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <app2_package/AddTwoIntsRequest.h>
#include <app2_package/AddTwoIntsResponse.h>


namespace app2_package
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace app2_package


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::app2_package::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::app2_package::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::app2_package::AddTwoInts > {
  static const char* value()
  {
    return "app2_package/AddTwoInts";
  }

  static const char* value(const ::app2_package::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::app2_package::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::app2_package::AddTwoInts >
template<>
struct MD5Sum< ::app2_package::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::app2_package::AddTwoInts >::value();
  }
  static const char* value(const ::app2_package::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::app2_package::AddTwoIntsRequest> should match
// service_traits::DataType< ::app2_package::AddTwoInts >
template<>
struct DataType< ::app2_package::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::app2_package::AddTwoInts >::value();
  }
  static const char* value(const ::app2_package::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::app2_package::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::app2_package::AddTwoInts >
template<>
struct MD5Sum< ::app2_package::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::app2_package::AddTwoInts >::value();
  }
  static const char* value(const ::app2_package::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::app2_package::AddTwoIntsResponse> should match
// service_traits::DataType< ::app2_package::AddTwoInts >
template<>
struct DataType< ::app2_package::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::app2_package::AddTwoInts >::value();
  }
  static const char* value(const ::app2_package::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APP2_PACKAGE_MESSAGE_ADDTWOINTS_H
